import type { RubberEntry } from "@/types/rubber";

const rubbers: RubberEntry[] = [
  {
    id: "zyre-03",
    name: "ザイア03",
    type: "裏ソフト",
    price: null,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "高い弧線と強い回転で、深いドライブやカウンターを狙いたい人",
    source: "https://www.butterfly.co.jp/products/detail/06140.html",
    officialNote:
      "ハイテンション／スプリング スポンジX／リコシート／スポンジ硬度44",
    verifiedAt: "2026-09-05",
  },
  {
    id: "dignics-09c",
    name: "ディグニクス09C",
    type: "裏ソフト",
    price: null,
    hardness: "硬",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "粘着系の強い回転とパワードライブを求める人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "スプリング スポンジX搭載",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dignics-05",
    name: "ディグニクス05",
    type: "裏ソフト",
    price: null,
    hardness: "中硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "回転量とカウンターの両方を重視する人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "スプリング スポンジX搭載",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dignics-80",
    name: "ディグニクス80",
    type: "裏ソフト",
    price: null,
    hardness: "中硬",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["counter", "control"],
    suitableFor: "攻守の切り替えを重視する人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "スプリング スポンジX搭載",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dignics-64",
    name: "ディグニクス64",
    type: "裏ソフト",
    price: null,
    hardness: "中硬",
    speed: 5,
    spin: 3,
    control: 3,
    styles: ["counter"],
    suitableFor: "前陣でのスピードとカウンターを求める人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "スプリング スポンジX搭載",
    verifiedAt: "2026-08-17",
  },
  {
    id: "tenergy-05",
    name: "テナジー05",
    type: "裏ソフト",
    price: null,
    hardness: "中硬",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["spin"],
    suitableFor: "ドライブ主体で回転を武器にしたい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "スプリング スポンジ搭載",
    verifiedAt: "2026-08-17",
  },
  {
    id: "tenergy-05fx",
    name: "テナジー05FX",
    type: "裏ソフト",
    price: null,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin", "control"],
    suitableFor: "回転性能と扱いやすさを両立したい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "スプリング スポンジ搭載",
    verifiedAt: "2026-08-17",
  },
  {
    id: "tenergy-80",
    name: "テナジー80",
    type: "裏ソフト",
    price: null,
    hardness: "中硬",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["counter", "control"],
    suitableFor: "オールラウンドな攻撃を組み立てたい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "スプリング スポンジ搭載",
    verifiedAt: "2026-08-17",
  },
  {
    id: "tenergy-64",
    name: "テナジー64",
    type: "裏ソフト",
    price: null,
    hardness: "中",
    speed: 5,
    spin: 3,
    control: 3,
    styles: ["counter"],
    suitableFor: "スピード感ある前陣攻撃をしたい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "スプリング スポンジ搭載",
    verifiedAt: "2026-08-17",
  },
  {
    id: "glayzer",
    name: "グレイザー",
    type: "裏ソフト",
    price: 6050,
    hardness: "中硬",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["spin", "control"],
    suitableFor: "回転系テンションの基本性能を求める人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "ハイテンション裏ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "glayzer-09c",
    name: "グレイザー09C",
    type: "裏ソフト",
    price: 6050,
    hardness: "硬",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "粘着系の回転を取り入れたい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "ハイテンション裏ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rozena",
    name: "ロゼナ",
    type: "裏ソフト",
    price: 5500,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 5,
    styles: ["control", "beginner"],
    suitableFor: "安定性を優先して攻撃技術を身につけたい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "ハイテンション裏ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "roundell",
    name: "ラウンデル",
    type: "裏ソフト",
    price: 4620,
    hardness: "中",
    speed: 4,
    spin: 3,
    control: 4,
    styles: ["counter", "beginner"],
    suitableFor: "スピードと扱いやすさの両方を求める人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "ハイテンション裏ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "tackiness-chop",
    name: "タキネス チョップ",
    type: "裏ソフト",
    price: 3080,
    hardness: "軟",
    speed: 2,
    spin: 5,
    control: 5,
    styles: ["defense"],
    suitableFor: "カットの回転量と安定を求める人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "裏ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "sriver",
    name: "スレイバー",
    type: "裏ソフト",
    price: 3520,
    hardness: "中",
    speed: 3,
    spin: 3,
    control: 4,
    styles: ["beginner"],
    suitableFor: "基本打法を反復して身につけたい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "裏ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "flextra",
    name: "フレクストラ",
    type: "裏ソフト",
    price: 2200,
    hardness: "軟",
    speed: 2,
    spin: 3,
    control: 5,
    styles: ["beginner"],
    suitableFor: "最初の一枚で基礎を固めたい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "裏ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "impartial-xs",
    name: "インパーシャルXS",
    type: "表ソフト",
    price: 5500,
    hardness: "中硬",
    speed: 5,
    spin: 3,
    control: 3,
    styles: ["shortPips"],
    suitableFor: "ミート・スマッシュを主軸に速攻したい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "表ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "speedy-po",
    name: "スピーディーP.O.",
    type: "表ソフト",
    price: 3080,
    hardness: "中",
    speed: 4,
    spin: 2,
    control: 4,
    styles: ["shortPips", "beginner"],
    suitableFor: "表ソフトの速攻技術を基礎から学びたい人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "表ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "feint-long-3",
    name: "フェイント ロング3",
    type: "粒高",
    price: 2750,
    hardness: "—",
    speed: 1,
    spin: 5,
    control: 4,
    styles: ["defense"],
    suitableFor: "粒高カットの変化と回転量を求める人",
    source: "https://www.butterfly.co.jp/products/rubber/",
    officialNote: "ツブ高ラバー",
    verifiedAt: "2026-08-17",
  },
];

export default rubbers;
