import type { RubberEntry } from "@/types/rubber";

const rubbers: RubberEntry[] = [
  {
    id: "bluegrip-j1",
    name: "ブルーグリップ J1",
    type: "裏ソフト",
    price: 8800,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "counter"],
    suitableFor: "粘着性と高速ドライブを両立したい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL107",
    officialNote: "ハイブリッド系裏ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluegrip-j2",
    name: "ブルーグリップ J2",
    type: "裏ソフト",
    price: 8800,
    hardness: "中硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "回転とパワーの両方を求める人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL108",
    officialNote: "ハイブリッド系裏ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluegrip-j3",
    name: "ブルーグリップ J3",
    type: "裏ソフト",
    price: 8800,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["sticky", "control"],
    suitableFor: "粘着系の球持ちを扱いやすく使いたい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL109",
    officialNote: "ハイブリッド系裏ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluestar-a1",
    name: "ブルースター A1",
    type: "裏ソフト",
    price: 10450,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["counter", "spin"],
    suitableFor: "上級攻撃型として強い球威を求める人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL101",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluestar-a2",
    name: "ブルースター A2",
    type: "裏ソフト",
    price: 10450,
    hardness: "中硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "高い回転とスピードをバランスよく求める人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL103",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluestar-a3",
    name: "ブルースター A3",
    type: "裏ソフト",
    price: 10450,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin", "control"],
    suitableFor: "高性能ラバーを柔らかめに使いたい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL104",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluestorm-pro",
    name: "ブルーストーム PRO",
    type: "裏ソフト",
    price: 9900,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["counter", "spin"],
    suitableFor: "プロ仕様の強い反発と回転を求める人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL097",
    officialNote: "プロ仕様セレクトモデル",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluestorm-pro-am",
    name: "ブルーストーム PRO AM",
    type: "裏ソフト",
    price: 9900,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin", "control"],
    suitableFor: "PRO系の性能をソフトに扱いたい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL098",
    officialNote: "プロ仕様ソフトモデル",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluestorm-z1",
    name: "ブルーストーム Z1",
    type: "裏ソフト",
    price: 7920,
    hardness: "中硬",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["spin"],
    suitableFor: "回転を重視したドライブ型の人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL086",
    officialNote: "ブルーストーム Zシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluestorm-z2",
    name: "ブルーストーム Z2",
    type: "裏ソフト",
    price: 7920,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter"],
    suitableFor: "スピード主体の前陣攻撃をしたい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL087",
    officialNote: "ブルーストーム Zシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "bluestorm-z3",
    name: "ブルーストーム Z3",
    type: "裏ソフト",
    price: 7920,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["control", "counter"],
    suitableFor: "打球感と扱いやすさを両立したい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL088",
    officialNote: "ブルーストーム Zシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "baracuda",
    name: "バラクーダ",
    type: "裏ソフト",
    price: 7590,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin"],
    suitableFor: "豊富な回転量をドライブに生かしたい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL043",
    officialNote: "スピン系裏ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "baxster-f1a",
    name: "バグスター F1-A",
    type: "表ソフト",
    price: 6600,
    hardness: "中",
    speed: 4,
    spin: 3,
    control: 4,
    styles: ["shortPips"],
    suitableFor: "表ソフトで球持ちとスピードを両立したい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL020",
    officialNote: "表ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "piranha-cd",
    name: "ピラニア CD",
    type: "粒高",
    price: 5500,
    hardness: "—",
    speed: 1,
    spin: 4,
    control: 5,
    styles: ["defense"],
    suitableFor: "守備での安定とクラシックな粒高の変化を求める人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL102",
    officialNote: "粒高ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "spike-p1",
    name: "スパイク P1",
    type: "粒高",
    price: 5500,
    hardness: "—",
    speed: 1,
    spin: 5,
    control: 4,
    styles: ["defense"],
    suitableFor: "粒高の変化と守備力を幅広く使いたい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL073",
    officialNote: "粒高ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "alligator-anti",
    name: "アリゲーター アンチ",
    type: "アンチ",
    price: 5720,
    hardness: "—",
    country: "中国",
    speed: 1,
    spin: 1,
    control: 5,
    styles: ["defense"],
    suitableFor: "硬質アンチで相手の回転を抑えたい人",
    source: "https://www.donic.jp/home/catalogue.php?pg=A/AL061",
    officialNote: "ハードタイプアンチラバー",
    verifiedAt: "2026-08-17",
  },
];

export default rubbers;
