import type { RubberEntry } from "@/types/rubber";

const rubbers: RubberEntry[] = [
  {
    id: "trinity-hugo-calderano-dynamic",
    name: "トリニティ ウーゴ カルデラノ ダイナミック",
    type: "裏ソフト",
    price: 12100,
    hardness: "硬",
    country: "ドイツ",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "強いスイングで回転と威力を両立したい人",
    source:
      "https://joola.co.jp/collections/table-tennis-rubbers-pimples-in-rubbers",
    officialNote: "JOOLA公式の裏ラバーカテゴリ掲載モデル",
    verifiedAt: "2026-08-18",
  },
  {
    id: "trinity-hugo-calderano-charge",
    name: "トリニティ ウーゴ カルデラノ チャージ",
    type: "裏ソフト",
    price: 12100,
    hardness: "中硬",
    country: "ドイツ",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "反発と回転のバランスで積極的に攻めたい人",
    source:
      "https://joola.co.jp/collections/table-tennis-rubbers-pimples-in-rubbers",
    officialNote: "JOOLA公式の裏ラバーカテゴリ掲載モデル",
    verifiedAt: "2026-08-18",
  },
  {
    id: "golden-tango",
    name: "ゴールデン タンゴ",
    type: "裏ソフト",
    price: 7480,
    hardness: "中硬",
    country: "ドイツ",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "粘着系の回転を使ってドライブを打ちたい人",
    source:
      "https://joola.co.jp/collections/table-tennis-rubbers-pimples-in-rubbers",
    officialNote: "JOOLA公式の裏ラバーカテゴリ掲載モデル",
    verifiedAt: "2026-08-18",
  },
  {
    id: "tango-ultra",
    name: "タンゴ ウルトラ",
    type: "表ソフト",
    price: 7590,
    hardness: "中",
    country: "ドイツ",
    speed: 4,
    spin: 3,
    control: 5,
    styles: ["shortPips", "control"],
    suitableFor: "表ソフトでブロックとミートを安定させたい人",
    source: "https://joola.co.jp/products/tango-ultra-table-tennis-rubber",
    officialNote: "スピードグルー効果内蔵テンション表ラバー",
    verifiedAt: "2026-08-18",
  },
  {
    id: "express-ultra",
    name: "エクスプレス ウルトラ",
    type: "表ソフト",
    price: 7970,
    hardness: "中",
    country: "ドイツ",
    speed: 5,
    spin: 3,
    control: 3,
    styles: ["shortPips"],
    suitableFor: "強い弾みを生かして速攻したい人",
    source: "https://joola.co.jp/products/express-ultra-table-tennis-rubber",
    officialNote: "スピード系テンション表ソフトラバー",
    verifiedAt: "2026-08-18",
  },
  {
    id: "allegro-s",
    name: "アレグロ S",
    type: "表ソフト",
    price: 7150,
    hardness: "中",
    country: "日本",
    speed: 4,
    spin: 3,
    control: 4,
    styles: ["shortPips", "control"],
    suitableFor: "表ソフトで反発とコントロールを両立したい人",
    source:
      "https://joola.co.jp/collections/table-tennis-rubbers-pimples-out-rubbers",
    officialNote: "JOOLA公式の表ラバーカテゴリ掲載モデル",
    verifiedAt: "2026-08-18",
  },
  {
    id: "adagio",
    name: "アダジオ",
    type: "表ソフト",
    price: 4807,
    hardness: "中",
    country: "日本",
    speed: 3,
    spin: 3,
    control: 5,
    styles: ["shortPips", "beginner"],
    suitableFor: "表ソフトの基本技術と安定感を身につけたい人",
    source:
      "https://joola.co.jp/collections/table-tennis-rubbers-pimples-out-rubbers",
    officialNote: "JOOLA公式の表ラバーカテゴリ掲載モデル",
    verifiedAt: "2026-08-18",
  },
  {
    id: "scordato",
    name: "スコルダート",
    type: "表ソフト",
    price: 5693,
    hardness: "中",
    country: "日本",
    speed: 4,
    spin: 3,
    control: 4,
    styles: ["shortPips"],
    suitableFor: "表ソフトで攻撃と安定をバランスよく使いたい人",
    source:
      "https://joola.co.jp/collections/table-tennis-rubbers-pimples-out-rubbers",
    officialNote: "JOOLA公式の表ラバーカテゴリ掲載モデル",
    verifiedAt: "2026-08-18",
  },
];

export default rubbers;
