import type { RubberEntry } from "@/types/rubber";

const rubbers: RubberEntry[] = [
  {
    id: "fastarc-g1",
    name: "ファスターク G-1",
    type: "裏ソフト",
    price: 7480,
    hardness: "中硬",
    country: "ドイツ",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin"],
    suitableFor: "スピンドライブを軸に攻めたい人",
    source: "https://www.nittaku.com/products/rubbers/pimples-in/",
    officialNote: "テンション系／スピンドライブ重視",
    verifiedAt: "2026-08-17",
  },
  {
    id: "fastarc-c1",
    name: "ファスターク C-1",
    type: "裏ソフト",
    price: 7260,
    hardness: "中",
    country: "ドイツ",
    speed: 4,
    spin: 4,
    control: 5,
    styles: ["control", "spin"],
    suitableFor: "バランス型のラリーを組み立てたい人",
    source: "https://www.nittaku.com/products/rubbers/pimples-in/",
    officialNote: "テンション系／バランスラリー重視",
    verifiedAt: "2026-08-17",
  },
  {
    id: "fastarc-s1",
    name: "ファスターク S-1",
    type: "裏ソフト",
    price: 5720,
    hardness: "中",
    country: "ドイツ",
    speed: 5,
    spin: 3,
    control: 3,
    styles: ["counter"],
    suitableFor: "スマッシュとスピードドライブを重視する人",
    source: "https://www.nittaku.com/products/rubbers/pimples-in/",
    officialNote: "テンション系／スピードスマッシュ重視",
    verifiedAt: "2026-08-17",
  },
  {
    id: "gennexion",
    name: "ジェネクション",
    type: "裏ソフト",
    price: 10780,
    hardness: "硬",
    country: "ドイツ",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "パワーと深い打球を求める人",
    source: "https://www.nittaku.com/products/rubbers/pimples-in/",
    officialNote: "テンション系／掴んで深く飛ばす",
    verifiedAt: "2026-08-17",
  },
  {
    id: "gennexion-v2c",
    name: "ジェネクション V2C",
    type: "裏ソフト",
    price: 10780,
    hardness: "硬",
    country: "ドイツ",
    speed: 5,
    spin: 5,
    control: 4,
    styles: ["sticky", "counter", "spin"],
    suitableFor:
      "微粘着の球持ちを生かし、台上技術と早い打点のカウンターを高めたい人",
    source: "https://www.nittaku.com/products/rubbers/post-71",
    officialNote:
      "微粘着テンション／デュアルトップシート・デュアルスポンジ／硬度42.5",
    verifiedAt: "2026-09-05",
  },
  {
    id: "hammond-z2",
    name: "ハモンド Z2",
    type: "裏ソフト",
    price: 7480,
    hardness: "中硬",
    country: "日本",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter"],
    suitableFor: "打ち負けにくさを重視して前陣で攻める人",
    source: "https://www.nittaku.com/products/rubbers/pimples-in/",
    officialNote: "ZC（ゼットチャージ）",
    verifiedAt: "2026-08-17",
  },
  {
    id: "flyatt-evo",
    name: "フライアット EVO",
    type: "裏ソフト",
    price: 4950,
    hardness: "中",
    country: "日本",
    speed: 4,
    spin: 3,
    control: 4,
    styles: ["counter", "beginner"],
    suitableFor: "扱いやすいスピード系を求める人",
    source: "https://www.nittaku.com/products/rubbers/pimples-in/",
    officialNote: "AC（アクティブチャージ）",
    verifiedAt: "2026-08-17",
  },
  {
    id: "blastac",
    name: "ブラスタック",
    type: "裏ソフト",
    price: 5720,
    hardness: "軟",
    country: "日本",
    speed: 4,
    spin: 4,
    control: 5,
    styles: ["control", "counter"],
    suitableFor: "柔らかな球持ちと安定した軌道を保ちながら攻撃力も求める人",
    source: "https://www.nittaku.com/products/rubbers/post-78",
    officialNote:
      "AC（アクティブチャージ）／カーボンブラックスポンジ／硬度35.0",
    verifiedAt: "2026-09-05",
  },
  {
    id: "kyohyo-8-80",
    name: "キョウヒョウ8-80",
    type: "裏ソフト",
    price: 6600,
    hardness: "中硬",
    country: "中国",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "粘着系を食い込ませて飛ばしたい人",
    source: "https://www.nittaku.com/products/rubbers/pimples-in/",
    officialNote: "粘着性／食い込ませて飛ばす",
    verifiedAt: "2026-08-17",
  },
  {
    id: "kyohyo-neo3",
    name: "キョウヒョウ ネオ3",
    type: "裏ソフト",
    price: 5720,
    hardness: "硬",
    country: "中国",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky"],
    suitableFor: "粘着性の強い回転を武器にしたい人",
    source: "https://www.nittaku.com/products/rubbers/post-20",
    officialNote: "粘着性／スピード重視",
    verifiedAt: "2026-08-18",
  },
  {
    id: "kyohyo-8-80-power",
    name: "キョウヒョウ8-80パワー",
    type: "裏ソフト",
    price: 7150,
    hardness: "中硬",
    country: "中国",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin", "counter"],
    suitableFor:
      "粘着の回転を生かしながら、反発力とバック面での扱いやすさも求める人",
    source: "https://www.nittaku.com/products/rubbers/post-73",
    officialNote: "AC内蔵／粘着性能を保ちつつパワー＋スピードドライブ",
    verifiedAt: "2026-08-18",
  },
  {
    id: "kyohyo-national-blue",
    name: "キョウヒョウ3国狂ブルー",
    type: "裏ソフト",
    price: 19800,
    hardness: "硬",
    country: "中国",
    speed: 5,
    spin: 5,
    control: 2,
    styles: ["sticky", "spin"],
    suitableFor:
      "高いスイングスピードで、ブルースポンジのパワードライブを引き出したい人",
    source: "https://www.nittaku.com/products/rubbers/post-61",
    officialNote:
      "紅双喜製ブルースポンジ／特厚・中国ナショナルチーム使用モデル",
    verifiedAt: "2026-08-18",
  },
  {
    id: "kyohyo-pro3-turbo-blue",
    name: "キョウヒョウプロ3-TURBO BLUE-",
    type: "裏ソフト",
    price: 7260,
    hardness: "硬",
    country: "中国",
    speed: 5,
    spin: 5,
    control: 2,
    styles: ["sticky", "spin", "counter"],
    suitableFor: "パワー系スイングで、粘着の強回転と破壊力を両立したい人",
    source: "https://www.nittaku.com/products/rubbers/post-18",
    officialNote: "AC内蔵日本製高弾性スポンジ／硬度50.0",
    verifiedAt: "2026-08-18",
  },
  {
    id: "kyohyo-pro3-turbo-orange",
    name: "キョウヒョウプロ3-TURBO ORANGE-",
    type: "裏ソフト",
    price: 6930,
    hardness: "中硬",
    country: "中国",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin", "control"],
    suitableFor:
      "粘着の回転と威力を保ちつつ、サービスや台上など細かなプレーも重視する人",
    source: "https://www.nittaku.com/products/rubbers/post-19",
    officialNote: "AC内蔵日本製高弾性スポンジ／硬度45.0",
    verifiedAt: "2026-08-18",
  },
  {
    id: "kyohyo-pro2",
    name: "キョウヒョウ プロ2",
    type: "裏ソフト",
    price: 5500,
    hardness: "硬",
    country: "中国",
    speed: 3,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "重い回転球を中心に、粘着ドライブで得点を狙いたい人",
    source: "https://www.nittaku.com/products/rubbers/post-21",
    officialNote: "回転重視シート／キョウヒョウIIのプロ仕様",
    verifiedAt: "2026-08-18",
  },
  {
    id: "kyohyo-pro3",
    name: "キョウヒョウ プロ3",
    type: "裏ソフト",
    price: 5500,
    hardness: "硬",
    country: "中国",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "粘着らしい強い回転とスピードの両方を求める人",
    source: "https://www.nittaku.com/products/rubbers/post-22",
    officialNote: "回転＋スピードタイプのシート／キョウヒョウIIIのプロ仕様",
    verifiedAt: "2026-08-18",
  },
  {
    id: "nittaku-kyohyo3",
    name: "ニッタク キョウヒョウ3",
    type: "裏ソフト",
    price: 4950,
    hardness: "中",
    country: "中国",
    speed: 3,
    spin: 4,
    control: 4,
    styles: ["sticky", "spin", "control"],
    suitableFor: "粘着系を初めて使う際に、日本製スポンジの扱いやすさも求める人",
    source: "https://www.nittaku.com/products/rubbers/post-24",
    officialNote: "キョウヒョウIIIのシート＋日本製スポンジ／硬度37.5",
    verifiedAt: "2026-08-18",
  },
  {
    id: "morist-df",
    name: "モリスト DF",
    type: "裏ソフト",
    price: 6050,
    hardness: "軟",
    country: "ドイツ",
    speed: 2,
    spin: 5,
    control: 5,
    styles: ["defense"],
    suitableFor: "攻守バランスを保ちながらカットしたい人",
    source: "https://www.nittaku.com/products/rubbers/pimples-in/",
    officialNote: "テンション系／カット用",
    verifiedAt: "2026-08-17",
  },
  {
    id: "stellack",
    name: "ステラック",
    type: "裏ソフト",
    price: 2970,
    hardness: "軟",
    country: "中国",
    speed: 2,
    spin: 3,
    control: 5,
    styles: ["beginner"],
    suitableFor: "基本打法を身につけたい入門者",
    source: "https://www.nittaku.com/products/rubbers/pimples-in/",
    officialNote: "コントロール系／入門者向け",
    verifiedAt: "2026-08-17",
  },
];

export default rubbers;
