import type { RubberEntry } from "@/types/rubber";

const rubbers: RubberEntry[] = [
  {
    id: "helix-platinum-m",
    name: "ヘリックスプラチナ M",
    type: "裏ソフト",
    price: null,
    hardness: "中硬",
    country: "ドイツ",
    speed: 5,
    spin: 5,
    control: 4,
    styles: ["spin", "counter", "control"],
    suitableFor: "高い弧線と回転を保ちながら、扱いやすさも重視する人",
    source: "https://stigasports.jp/products/5108",
    officialNote: "Optimized Energy Sponge／硬度47.5°",
    verifiedAt: "2026-09-05",
  },
  {
    id: "helix-platinum-h",
    name: "ヘリックスプラチナ H",
    type: "裏ソフト",
    price: null,
    hardness: "硬",
    country: "ドイツ",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "高い弧線とスピードのバランスで攻撃したい人",
    source: "https://stigasports.jp/products/5106",
    officialNote: "Optimized Energy Sponge／硬度50°",
    verifiedAt: "2026-09-05",
  },
  {
    id: "helix-platinum-xh",
    name: "ヘリックスプラチナ XH",
    type: "裏ソフト",
    price: null,
    hardness: "硬",
    country: "ドイツ",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "強いインパクトでパワーとコントロールの両立を狙う人",
    source: "https://stigasports.jp/helix",
    officialNote: "Optimized Energy Sponge／硬度52.5°／モーレゴード使用モデル",
    verifiedAt: "2026-09-05",
  },
  {
    id: "helix-platinum-55",
    name: "ヘリックスプラチナ 55",
    type: "裏ソフト",
    price: null,
    hardness: "硬",
    country: "ドイツ",
    speed: 5,
    spin: 5,
    control: 2,
    styles: ["spin", "counter"],
    suitableFor: "高硬度スポンジを生かして最大級のスピードを引き出したい人",
    source: "https://stigasports.jp/products/5095",
    officialNote: "Optimized Energy Sponge／硬度55°",
    verifiedAt: "2026-09-05",
  },
  {
    id: "dna-dragon-power-525",
    name: "DNA ドラゴンパワー 52.5",
    type: "裏ソフト",
    price: 9350,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "微粘着のグリップとパワードライブを求める人",
    source: "https://stigasports.jp/products/2965",
    officialNote: "微粘着テンション／硬度52.5°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dna-dragon-power-55",
    name: "DNA ドラゴンパワー 55",
    type: "裏ソフト",
    price: 9350,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "counter"],
    suitableFor: "硬めの微粘着で打ち合いの威力を求める人",
    source: "https://stigasports.jp/products/2972",
    officialNote: "微粘着テンション／硬度55°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dna-hybrid-h",
    name: "DNA ハイブリッド H",
    type: "裏ソフト",
    price: 9900,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "回転系技術とスピードのバランスを高水準で求める人",
    source: "https://stigasports.jp/products/2358",
    officialNote: "ハイブリッドテンション",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dna-hybrid-m",
    name: "DNA ハイブリッド M",
    type: "裏ソフト",
    price: 9900,
    hardness: "中硬",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["sticky", "control"],
    suitableFor: "ハイブリッドの回転を扱いやすい硬さで選びたい人",
    source: "https://stigasports.jp/products/2364",
    officialNote: "ハイブリッドテンション",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dna-pro-h",
    name: "DNA プロ H",
    type: "裏ソフト",
    price: 7590,
    hardness: "硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter", "spin"],
    suitableFor: "ボールの重さとスピードで勝負したい人",
    source: "https://stigasports.jp/products/1450",
    officialNote: "テンション系／硬度50°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dna-pro-m",
    name: "DNA プロ M",
    type: "裏ソフト",
    price: 7590,
    hardness: "中硬",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin", "counter"],
    suitableFor: "球持ちと弾みのバランスを求める人",
    source: "https://stigasports.jp/products/1454",
    officialNote: "テンション系／硬度47.5°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dna-pro-s",
    name: "DNA プロ S",
    type: "裏ソフト",
    price: 7590,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 5,
    styles: ["control", "spin"],
    suitableFor: "球持ちとコントロール性能を重視する人",
    source: "https://stigasports.jp/products/1457",
    officialNote: "テンション系／硬度42.5°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "dna-future-m",
    name: "DNA フューチャー M",
    type: "裏ソフト",
    price: 4180,
    hardness: "中硬",
    speed: 3,
    spin: 4,
    control: 5,
    styles: ["beginner", "control"],
    suitableFor: "グリップとコントロールを優先して基礎を学ぶ人",
    source: "https://stigasports.jp/products/1460",
    officialNote: "ドイツ製裏ソフト／硬度47.5°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "mantra-pro-m",
    name: "マントラ プロ M",
    type: "裏ソフト",
    price: 5940,
    hardness: "中硬",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["counter", "control"],
    suitableFor: "弾きとコントロールをバランスよく使いたい人",
    source: "https://stigasports.jp/products/1474",
    officialNote: "日本製テンション／硬度47°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "mantra-pro-h",
    name: "マントラ プロ H",
    type: "裏ソフト",
    price: 5940,
    hardness: "硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter"],
    suitableFor: "前陣からのスピードとコース取りを重視する人",
    source: "https://stigasports.jp/products/1471",
    officialNote: "日本製テンション／硬度50°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "mantra-pro-xh",
    name: "マントラ プロ XH",
    type: "裏ソフト",
    price: 5940,
    hardness: "硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter"],
    suitableFor: "早い球離れで前陣攻撃をしたい人",
    source: "https://stigasports.jp/products/1466",
    officialNote: "日本製テンション／硬度53°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "mantra-control",
    name: "マントラ コントロール",
    type: "裏ソフト",
    price: 3520,
    hardness: "軟",
    speed: 2,
    spin: 3,
    control: 5,
    styles: ["beginner"],
    suitableFor: "基本打法と回転のかけ方を身につけたい人",
    source: "https://stigasports.jp/products/2462",
    officialNote: "日本製裏ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "symmetry",
    name: "シンメトリー",
    type: "表ソフト",
    price: 4730,
    hardness: "中",
    speed: 4,
    spin: 3,
    control: 4,
    styles: ["shortPips", "control"],
    suitableFor: "表ソフトでブロックと回転系攻撃を使い分けたい人",
    source: "https://stigasports.jp/products/1494",
    officialNote: "日本製テンション系表ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "clippa",
    name: "クリッパ",
    type: "表ソフト",
    price: 3300,
    hardness: "中",
    speed: 4,
    spin: 3,
    control: 4,
    styles: ["shortPips"],
    suitableFor: "表ソフトでドライブとスマッシュを両立したい人",
    source: "https://stigasports.jp/products/1496",
    officialNote: "表ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vertical-20",
    name: "バーティカル 20",
    type: "粒高",
    price: 4290,
    hardness: "—",
    speed: 1,
    spin: 4,
    control: 5,
    styles: ["defense"],
    suitableFor: "粒高を初めて使い、抑えと攻撃を両立したい人",
    source: "https://stigasports.jp/products/1500",
    officialNote: "縦目粒高ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "horizontal-55",
    name: "ホリゾンタル 55",
    type: "粒高",
    price: 4290,
    hardness: "—",
    speed: 1,
    spin: 5,
    control: 4,
    styles: ["defense"],
    suitableFor: "横目粒高の大きな変化で惑わせたい人",
    source: "https://stigasports.jp/products/1512",
    officialNote: "横目粒高ラバー",
    verifiedAt: "2026-08-17",
  },
];

export default rubbers;
