import type { RubberEntry } from "@/types/rubber";

const rubbers: RubberEntry[] = [
  {
    id: "hybrid-k3",
    name: "ハイブリッド K3",
    type: "裏ソフト",
    price: 8910,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "粘着テンションの強回転と反発を求める人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "回転系テンション／硬度53",
    verifiedAt: "2026-08-17",
  },
  {
    id: "hybrid-k3-fx",
    name: "ハイブリッド K3 FX",
    type: "裏ソフト",
    price: 8910,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["sticky", "control"],
    suitableFor: "粘着テンションの回転を扱いやすくしたい人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "粘着系テンション／硬度48",
    verifiedAt: "2026-08-17",
  },
  {
    id: "hybrid-mk",
    name: "ハイブリッド MK",
    type: "裏ソフト",
    price: 7920,
    hardness: "中硬",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin", "control"],
    suitableFor: "弧線・球持ち・威力を高い水準で求める人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "回転系テンション／硬度48",
    verifiedAt: "2026-08-17",
  },
  {
    id: "hybrid-mk-fx",
    name: "ハイブリッド MK FX",
    type: "裏ソフト",
    price: 7920,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 5,
    styles: ["spin", "control"],
    suitableFor: "柔らかな打球感で高い回転を求める人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "回転系テンション／硬度44",
    verifiedAt: "2026-08-17",
  },
  {
    id: "evolution-mxd",
    name: "エボリューション MX-D",
    type: "裏ソフト",
    price: 7810,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "威力と安定感を両立した高性能ラバーを求める人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "回転系テンション／硬度51.5",
    verifiedAt: "2026-08-17",
  },
  {
    id: "evolution-eld",
    name: "エボリューション EL-D",
    type: "裏ソフト",
    price: 7810,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin", "control"],
    suitableFor: "高い回転性能を保ちつつ硬さを抑えたい人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "回転系テンション／硬度46",
    verifiedAt: "2026-08-17",
  },
  {
    id: "evolution-fxd",
    name: "エボリューション FX-D",
    type: "裏ソフト",
    price: 7810,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 5,
    styles: ["control"],
    suitableFor: "威力を保ちながら扱いやすさを重視する人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "回転系テンション／硬度44",
    verifiedAt: "2026-08-17",
  },
  {
    id: "evolution-mxp",
    name: "エボリューション MX-P",
    type: "裏ソフト",
    price: 7260,
    hardness: "中硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "中・上級の攻撃型で回転と飛距離を求める人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "回転系テンション／硬度45.7〜47.7",
    verifiedAt: "2026-08-17",
  },
  {
    id: "evolution-elp",
    name: "エボリューション EL-P",
    type: "裏ソフト",
    price: 7260,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["control", "spin"],
    suitableFor: "回転性能と使いやすさを両立したい人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "回転系テンション／硬度42.4〜44.4",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rapid",
    name: "ラピッド",
    type: "裏ソフト",
    price: 4180,
    hardness: "中",
    speed: 3,
    spin: 3,
    control: 5,
    styles: ["beginner", "control"],
    suitableFor: "高弾性ラバーで基礎と安定を両立したい人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "高弾性／硬度42.5",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rapid-soft",
    name: "ラピッドソフト",
    type: "裏ソフト",
    price: 4180,
    hardness: "軟",
    speed: 2,
    spin: 3,
    control: 5,
    styles: ["beginner"],
    suitableFor: "柔らかな感覚でコントロールを磨きたい人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "コントロール系／硬度35",
    verifiedAt: "2026-08-17",
  },
  {
    id: "speedy-soft",
    name: "スピーディーソフト",
    type: "表ソフト",
    price: 5170,
    hardness: "中",
    speed: 4,
    spin: 3,
    control: 5,
    styles: ["shortPips", "control"],
    suitableFor: "扱いやすい表ソフトで速攻を始めたい人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "コントロール系表ソフト／硬度45",
    verifiedAt: "2026-08-17",
  },
  {
    id: "speedy-soft-dtecs",
    name: "スピーディーソフトD.TecS",
    type: "表ソフト",
    price: 6105,
    hardness: "軟",
    speed: 5,
    spin: 3,
    control: 3,
    styles: ["shortPips"],
    suitableFor: "表ソフトのスピードと変化を強く出したい人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "テンション表ソフト／硬度35",
    verifiedAt: "2026-08-17",
  },
  {
    id: "grass-dtecs",
    name: "グラスD.TecS",
    type: "粒高",
    price: 6655,
    hardness: "—",
    speed: 1,
    spin: 5,
    control: 4,
    styles: ["defense"],
    suitableFor: "粒高の大きな変化と攻撃力を使いたい人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "ハイテンション粒高",
    verifiedAt: "2026-08-17",
  },
  {
    id: "grass-dtecs-gs",
    name: "グラスD.TecS GS",
    type: "粒高",
    price: 7095,
    hardness: "—",
    speed: 1,
    spin: 5,
    control: 4,
    styles: ["defense"],
    suitableFor: "接着シート付き粒高で変化を出したい人",
    source: "https://tibhar-japan.com/rubber/",
    officialNote: "ハイテンション粒高／OX",
    verifiedAt: "2026-08-17",
  },
];

export default rubbers;
