import type { RubberEntry } from "@/types/rubber";

const rubbers: RubberEntry[] = [
  {
    id: "v15-sticky",
    name: "V>15 スティッキー",
    type: "裏ソフト",
    price: 8580,
    hardness: "硬",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "微粘着の強回転と反発を両立したい人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "微粘着テンション系",
    verifiedAt: "2026-08-17",
  },
  {
    id: "v15-sticky-soft",
    name: "V>15 スティッキー ソフト",
    type: "裏ソフト",
    price: 8580,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["sticky", "control"],
    suitableFor: "粘着系の回転を扱いやすく取り入れたい人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "微粘着テンション系",
    verifiedAt: "2026-08-17",
  },
  {
    id: "v22-double-extra",
    name: "V>22 ダブルエキストラ",
    type: "裏ソフト",
    price: 8800,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "高い打球威力で主導権を握りたい人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "v20-extra",
    name: "V>20 エキストラ",
    type: "裏ソフト",
    price: 7260,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter"],
    suitableFor: "前陣から中陣の攻撃力を求める人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "v15-extra",
    name: "V>15 エキストラ",
    type: "裏ソフト",
    price: 7260,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter", "spin"],
    suitableFor: "攻撃のスピードと回転を両立したい人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "v15-stiff",
    name: "V>15 スティフ",
    type: "裏ソフト",
    price: 7260,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter"],
    suitableFor: "硬めの打球感でパワーを伝えたい人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "v15-limber",
    name: "V>15 リンバー",
    type: "裏ソフト",
    price: 7260,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["counter", "control"],
    suitableFor: "弾みと球持ちのバランスを求める人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "ventus-extra",
    name: "ヴェンタス エキストラ",
    type: "裏ソフト",
    price: 6050,
    hardness: "中硬",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["spin", "counter"],
    suitableFor: "攻撃型テンションをバランスよく使いたい人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "ventus-stiff",
    name: "ヴェンタス スティフ",
    type: "裏ソフト",
    price: 5610,
    hardness: "中硬",
    speed: 4,
    spin: 4,
    control: 3,
    styles: ["counter"],
    suitableFor: "しっかりした打球感の前陣攻撃を求める人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "ventus-limber",
    name: "ヴェンタス リンバー",
    type: "裏ソフト",
    price: 5610,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["control", "beginner"],
    suitableFor: "扱いやすい攻撃型ラバーを求める人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "ventus-regular-alpha",
    name: "ヴェンタス レギュラー アルファ",
    type: "裏ソフト",
    price: 3520,
    hardness: "軟",
    speed: 3,
    spin: 3,
    control: 5,
    styles: ["beginner"],
    suitableFor: "基本技術とコントロールを優先する人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vj-next",
    name: "VJ>ネクスト",
    type: "裏ソフト",
    price: 3080,
    hardness: "中",
    speed: 3,
    spin: 3,
    control: 4,
    styles: ["beginner"],
    suitableFor: "無理のない価格で攻撃技術を練習したい人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "triple-extra",
    name: "トリプル エキストラ",
    type: "裏ソフト",
    price: 5500,
    hardness: "硬",
    country: "中国",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "強粘着の回転と球威を生かして、粘着ドライブを軸に組み立てる人",
    source: "https://www.victas.com/products/detail.html?id=54",
    officialNote: "中国製強粘着裏ソフト／硬度55.0±3",
    verifiedAt: "2026-08-25",
  },
  {
    id: "triple-double-extra",
    name: "トリプル ダブルエキストラ",
    type: "裏ソフト",
    price: 5940,
    hardness: "硬",
    country: "中国",
    speed: 5,
    spin: 5,
    control: 2,
    styles: ["sticky", "spin", "counter"],
    suitableFor: "高い打球威力と強烈な粘着回転を引き出せる上級攻撃型の人",
    source: "https://www.victas.com/products/detail.html?id=53",
    officialNote: "中国製強粘着裏ソフト／硬度57.5±3",
    verifiedAt: "2026-08-25",
  },
  {
    id: "triple-regular",
    name: "トリプル レギュラー",
    type: "裏ソフト",
    price: 4400,
    hardness: "中",
    country: "中国",
    speed: 3,
    spin: 5,
    control: 4,
    styles: ["sticky", "spin", "control", "beginner"],
    suitableFor: "中国製強粘着を初中級者向けの扱いやすさで試したい人",
    source: "https://www.victas.com/products/detail.html?id=55",
    officialNote: "中国製強粘着裏ソフト／硬度42.5±3",
    verifiedAt: "2026-08-25",
  },
  {
    id: "vs401",
    name: "VS>401",
    type: "裏ソフト",
    price: 5720,
    hardness: "中硬",
    speed: 2,
    spin: 5,
    control: 5,
    styles: ["defense"],
    suitableFor: "切れたカットと守備の安定を求める人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "裏ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "curl-p1v",
    name: "カール P1V",
    type: "粒高",
    price: 4620,
    hardness: "—",
    speed: 1,
    spin: 5,
    control: 4,
    styles: ["defense"],
    suitableFor: "粒高の切れたカットと変化を使いたい人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "粒高ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "curl-p3v",
    name: "カール P3V",
    type: "粒高",
    price: 4620,
    hardness: "—",
    speed: 1,
    spin: 4,
    control: 5,
    styles: ["defense"],
    suitableFor: "粒高で守備の安定性を求める人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "粒高ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vo-102",
    name: "VO>102",
    type: "表ソフト",
    price: 6050,
    hardness: "中",
    speed: 5,
    spin: 3,
    control: 3,
    styles: ["shortPips"],
    suitableFor: "表ソフトで回転とミートを使い分けたい人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "表ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "spectol-s1",
    name: "スペクトル S1",
    type: "表ソフト",
    price: 4620,
    hardness: "中",
    speed: 5,
    spin: 2,
    control: 4,
    styles: ["shortPips"],
    suitableFor: "表ソフトでの速攻とミートを重視する人",
    source: "https://www.victas.com/products/?cat=3",
    officialNote: "表ソフトラバー",
    verifiedAt: "2026-08-17",
  },
];

export default rubbers;
