import type { RubberEntry } from "@/types/rubber";

const rubbers: RubberEntry[] = [
  {
    id: "omega-8-china",
    name: "オメガ8 チャイナ",
    type: "裏ソフト",
    price: 9680,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "中国ラバー系の強い回転と威力を求める人",
    source: "https://m.xiom.jp/",
    officialNote: "オメガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "omega-8-hybrid",
    name: "オメガ8 ハイブリッド",
    type: "裏ソフト",
    price: 7920,
    hardness: "中硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "counter"],
    suitableFor: "ハイブリッド系で回転と反発を両立したい人",
    source: "https://m.xiom.jp/",
    officialNote: "オメガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "omega-8-pro",
    name: "オメガ8 プロ",
    type: "裏ソフト",
    price: 7920,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "高い攻撃力で主導権を取りたい人",
    source: "https://m.xiom.jp/",
    officialNote: "オメガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "omega-8-euro",
    name: "オメガ8 ヨーロ",
    type: "裏ソフト",
    price: 7920,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 4,
    styles: ["counter", "control"],
    suitableFor: "スピードと扱いやすさを高水準で求める人",
    source: "https://m.xiom.jp/",
    officialNote: "オメガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "jekyll-c575",
    name: "ジキル＆ハイド C57.5",
    type: "裏ソフト",
    price: 11000,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 2,
    styles: ["sticky"],
    suitableFor: "強いインパクトで最大限の威力を引き出す人",
    source: "https://m.xiom.jp/",
    officialNote: "ジキル＆ハイドシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "jekyll-z525",
    name: "ジキル＆ハイド Z52.5",
    type: "裏ソフト",
    price: 11000,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 2,
    styles: ["counter", "spin"],
    suitableFor: "高硬度で威力のある攻撃を求める人",
    source: "https://m.xiom.jp/",
    officialNote: "ジキル＆ハイドシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "jekyll-v475",
    name: "ジキル＆ハイド V47.5",
    type: "裏ソフト",
    price: 8470,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin", "control"],
    suitableFor: "高性能ラバーを扱いやすい硬さで選びたい人",
    source: "https://m.xiom.jp/",
    officialNote: "ジキル＆ハイドシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vega-x",
    name: "ヴェガ X",
    type: "裏ソフト",
    price: 5500,
    hardness: "中硬",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["spin", "counter"],
    suitableFor: "攻撃型テンションをバランスよく使いたい人",
    source: "https://m.xiom.jp/",
    officialNote: "ヴェガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vega-tour",
    name: "ヴェガ ツアー",
    type: "裏ソフト",
    price: 6050,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "硬めの打球感で回転と威力を求める人",
    source: "https://m.xiom.jp/",
    officialNote: "ヴェガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vega-pro",
    name: "ヴェガ プロ",
    type: "裏ソフト",
    price: 5500,
    hardness: "中硬",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin"],
    suitableFor: "回転重視のドライブで攻めたい人",
    source: "https://m.xiom.jp/",
    officialNote: "ヴェガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vega-asia",
    name: "ヴェガ アジア",
    type: "裏ソフト",
    price: 5280,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter"],
    suitableFor: "直線的な攻撃とカウンターを重視する人",
    source: "https://m.xiom.jp/",
    officialNote: "ヴェガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vega-europe",
    name: "ヴェガ ヨーロッパ",
    type: "裏ソフト",
    price: 5280,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 5,
    styles: ["control", "spin"],
    suitableFor: "柔らかめで回転と安定を求める人",
    source: "https://m.xiom.jp/",
    officialNote: "ヴェガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vega-japan",
    name: "ヴェガ ジャパン",
    type: "裏ソフト",
    price: 5720,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 4,
    styles: ["counter", "spin"],
    suitableFor: "スピードと回転の両立を求める人",
    source: "https://m.xiom.jp/",
    officialNote: "ヴェガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vega-elite",
    name: "ヴェガ エリート",
    type: "裏ソフト",
    price: 5280,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 5,
    styles: ["control"],
    suitableFor: "扱いやすいテンションで安定を求める人",
    source: "https://m.xiom.jp/",
    officialNote: "ヴェガシリーズ",
    verifiedAt: "2026-08-17",
  },
  {
    id: "vega-intro",
    name: "ヴェガ イントロ",
    type: "裏ソフト",
    price: 3850,
    hardness: "中",
    speed: 3,
    spin: 3,
    control: 5,
    styles: ["beginner"],
    suitableFor: "入門用にテンション系の感覚を学びたい人",
    source: "https://m.xiom.jp/",
    officialNote: "ヴェガシリーズ",
    verifiedAt: "2026-08-17",
  },
];

export default rubbers;
