import type { RubberEntry } from "@/types/rubber";

const rubbers: RubberEntry[] = [
  {
    id: "rakza-xx",
    name: "ラクザXX",
    type: "裏ソフト",
    price: 7920,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "強烈な回転とスピードで打ち合いたい人",
    source: "https://www.yasakajp.com/items/rakza-xx/",
    officialNote: "ハイブリッドエナジー型／硬度47〜52°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rakza-x",
    name: "ラクザ X",
    type: "裏ソフト",
    price: 6930,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter", "spin"],
    suitableFor: "相手の回転に負けない前陣攻撃を求める人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "ハイブリッドエナジー型",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rakza-x-soft",
    name: "ラクザX ソフト",
    type: "裏ソフト",
    price: 6930,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["control", "spin"],
    suitableFor: "ラクザXの性能を柔らかめに扱いたい人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "ハイブリッドエナジー型",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rakza-z",
    name: "ラクザZ",
    type: "裏ソフト",
    price: 6930,
    hardness: "硬",
    speed: 4,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin"],
    suitableFor: "粘着性を生かした強い回転を求める人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "ハイブリッドエナジー型",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rakza-z-eh",
    name: "ラクザZ エクストラハード",
    type: "裏ソフト",
    price: 6930,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 2,
    styles: ["sticky"],
    suitableFor: "硬めの粘着系でパワードライブを狙う人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "ハイブリッドエナジー型",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rakza-7",
    name: "ラクザ 7",
    type: "裏ソフト",
    price: 6380,
    hardness: "中硬",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin"],
    suitableFor: "回転量の多いドライブを安定して打ちたい人",
    source: "https://www.yasakajp.com/items/rakza_7/",
    officialNote: "ハイブリッドエナジー型／硬度45〜50°",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rakza-7-soft",
    name: "ラクザ 7 ソフト",
    type: "裏ソフト",
    price: 6380,
    hardness: "中",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["spin", "control"],
    suitableFor: "高回転をソフトな打球感で扱いたい人",
    source: "https://www.yasakajp.com/items/rakza_7_soft/",
    officialNote: "ハイブリッドエナジー型",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rakza-7-hard",
    name: "ラクザ7ハード",
    type: "裏ソフト",
    price: 6380,
    hardness: "硬",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["spin", "counter"],
    suitableFor: "ラクザ7の回転を硬めの打球感で引き出す人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "ハイブリッドエナジー型",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rakza-9",
    name: "ラクザ 9",
    type: "裏ソフト",
    price: 6380,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["counter"],
    suitableFor: "スピードのあるドライブとカウンターを重視する人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "ハイブリッドエナジー型",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rigan",
    name: "ライガン",
    type: "裏ソフト",
    price: 4620,
    hardness: "中",
    speed: 3,
    spin: 4,
    control: 5,
    styles: ["control", "beginner"],
    suitableFor: "安定感を保ちながら攻撃技術を覚えたい人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "ハイブリッドエナジー型",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rigan-spin",
    name: "ライガンスピン",
    type: "裏ソフト",
    price: 4840,
    hardness: "中",
    speed: 3,
    spin: 5,
    control: 4,
    styles: ["spin", "control"],
    suitableFor: "扱いやすさを保って回転量を高めたい人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "ハイブリッドエナジー型",
    verifiedAt: "2026-08-17",
  },
  {
    id: "shining-dragon-2",
    name: "輝龍II",
    type: "裏ソフト",
    price: 5500,
    hardness: "中硬",
    country: "中国",
    speed: 4,
    spin: 5,
    control: 4,
    styles: ["sticky", "spin", "control"],
    suitableFor: "粘着の回転を保ちながら、扱いやすさも重視する人",
    source: "https://www.yasakajp.com/items/shining-dragon2/",
    officialNote: "中国製テンション系粘着裏ソフト／硬度45〜50°",
    verifiedAt: "2026-08-25",
  },
  {
    id: "rising-dragon-2",
    name: "翔龍II",
    type: "裏ソフト",
    price: 5500,
    hardness: "硬",
    country: "中国",
    speed: 5,
    spin: 5,
    control: 3,
    styles: ["sticky", "spin", "counter"],
    suitableFor: "強いスピンとパワードライブで、粘着系の威力を高めたい人",
    source: "https://www.yasakajp.com/items/rising-dragon2/",
    officialNote: "中国製テンション系粘着裏ソフト／硬度47〜52°",
    verifiedAt: "2026-08-25",
  },
  {
    id: "mark-v",
    name: "マーク V",
    type: "裏ソフト",
    price: 3520,
    hardness: "中",
    speed: 3,
    spin: 3,
    control: 5,
    styles: ["beginner"],
    suitableFor: "基本打法を丁寧に身につけたい人",
    source: "https://www.yasakajp.com/items/markv/",
    officialNote: "高弾性裏ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "original-extra",
    name: "オリジナルエクストラ",
    type: "裏ソフト",
    price: 2970,
    hardness: "軟",
    speed: 2,
    spin: 3,
    control: 5,
    styles: ["beginner"],
    suitableFor: "最初の一枚で基本技術を練習する人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "コントロール系裏ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "anti-power",
    name: "アンチパワー",
    type: "アンチ",
    price: 3080,
    hardness: "—",
    speed: 1,
    spin: 1,
    control: 5,
    styles: ["defense"],
    suitableFor: "アンチで相手の回転を抑えて変化を出す人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "アンチスピン裏ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "trick-anti",
    name: "トリックアンチ",
    type: "アンチ",
    price: 4400,
    hardness: "—",
    speed: 1,
    spin: 2,
    control: 4,
    styles: ["defense"],
    suitableFor: "アンチの変化と守備の組み立てを求める人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "アンチスピン裏ソフト",
    verifiedAt: "2026-08-17",
  },
  {
    id: "rakza-po",
    name: "ラクザ PO",
    type: "表ソフト",
    price: 6380,
    hardness: "中硬",
    speed: 5,
    spin: 4,
    control: 3,
    styles: ["shortPips"],
    suitableFor: "表ソフトでも回転と攻撃力を両立したい人",
    source: "https://www.yasakajp.com/goods/osr/",
    officialNote: "表ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "spinate",
    name: "スピネイト",
    type: "表ソフト",
    price: 5500,
    hardness: "中",
    speed: 4,
    spin: 4,
    control: 4,
    styles: ["shortPips"],
    suitableFor: "表ソフトで回転を生かした攻撃をする人",
    source: "https://www.yasakajp.com/goods/osr/",
    officialNote: "表ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "elfrark-rf",
    name: "エルフラークRF",
    type: "表ソフト",
    price: 4400,
    hardness: "中",
    speed: 4,
    spin: 3,
    control: 4,
    styles: ["shortPips", "control"],
    suitableFor: "変化と安定を両立する表ソフトを求める人",
    source: "https://www.yasakajp.com/goods/osr/",
    officialNote: "表ソフトラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "phantom-007",
    name: "ファントム 007",
    type: "粒高",
    price: 2530,
    hardness: "—",
    speed: 1,
    spin: 4,
    control: 4,
    styles: ["defense"],
    suitableFor: "粒高カットの基礎を身につけたい人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "粒高ラバー",
    verifiedAt: "2026-08-17",
  },
  {
    id: "phantom-0011",
    name: "ファントム 0011∞",
    type: "粒高",
    price: 2970,
    hardness: "—",
    speed: 1,
    spin: 5,
    control: 4,
    styles: ["defense"],
    suitableFor: "粒高で強い変化と切れを出したい人",
    source: "https://www.yasakajp.com/goods/rub/",
    officialNote: "粒高ラバー",
    verifiedAt: "2026-08-17",
  },
];

export default rubbers;
